### ISSUE TITLE
[redesign] Implement the card component

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#210]
![Screenshot 2019-08-30 at 16 00 58](https://user-images.githubusercontent.com/594890/64030929-68044800-cb3f-11e9-9cef-bc9b329ed2c7.png)
![Screenshot 2019-08-30 at 16 01 05](https://user-images.githubusercontent.com/594890/64030937-6a66a200-cb3f-11e9-94d2-cc5b92c2da7e.png)

## Todo 

- [x] have the ability for a card image that can be on top or to the left
- [x] decide if we're going to have an api `<EsCard @title="something" />` or if the title will just be a part of the yielded "card-body"
- [x] rename class "card-content" to be "card-body"

**Comment by mansona** [comment]
closed in #218
